[[extensions]]
type = "flow_trigger"
handle = "review-created-v5"
name = "Review Created"
description = "Triggers when a new review is submitted via Empire Reviews."
uid = "e57dbe6f-04ba-889d-0708-c2370608023bf879bd40"

[settings]
  [[settings.fields]]
  key = "rating"
  type = "number_integer"
  description = "Review Rating (1-5)"

  [[settings.fields]]
  key = "reviewBody"
  type = "multi_line_text_field"
  description = "Review Content"

  [[settings.fields]]
  key = "customerEmail"
  type = "email"
  description = "Customer Email Address"

  [[settings.fields]]
  key = "customerName"
  type = "single_line_text_field"
  description = "Customer Name"

  [[settings.fields]]
  key = "reviewTitle"
  type = "single_line_text_field"
  description = "Review Title"
