[[extensions]]

uid = "543b9057-d08a-1f63-f254-2bbcdb85403e7f073496"

type = "flow_trigger"
handle = "review-created-v3"
name = "Review Created v3"
description = "Triggers when a new review is submitted via Empire Reviews."

[settings]
  [[settings.fields]]
  key = "rating"
  type = "number_integer"

  [[settings.fields]]
  key = "reviewBody"
  type = "multi_line_text_field"

  [[settings.fields]]
  key = "customerEmail"
  type = "email"

  [[settings.fields]]
  key = "customerName"
  type = "single_line_text_field"

  [[settings.fields]]
  key = "reviewTitle"
  type = "single_line_text_field"
